---
postgresConnString: "host={{databaseEndpoint}} user=ashketchum password=squirtle123 port=5432 database=postgres sslmode=disable"

poolingConfig:
  maxWaitTimeForTrace: 10m
  retryDelay: 5s

googleAnalytics:
  enabled: false

demo:
  enabled: []

experimentalFeatures: []

telemetry:
  dataStores:
    opensearch:
      type: opensearch
      opensearch:
        addresses:
          - https://{{openSearchDomain}}
        index: otel-v1-apm-span-000001
        username: ashketchum
        password: Squirtle123@

  exporters:
    collector:
      serviceName: tracetest
      sampling: 100
      exporter:
        type: collector
        collector:
          endpoint: localhost:4317

server:
  telemetry:
    dataStore: opensearch
    exporter: collector
    applicationExporter: collector
