receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:

  filter:
    error_mode: ignore
    traces:
      span:
        - 'trace_state["tracetest"] != "true"'

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/trace:
    endpoint: tracetest-agent:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter, batch]
      exporters: [otlp]
    traces/agent:
      receivers: [otlp]
      processors: [filter, batch]
      exporters: [otlp/trace]
