receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:

  tail_sampling:
    decision_wait: 2s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
        {
          name: Accept traces that started from tracetest,
          type: trace_state,
          trace_state: { key: "tracetest", values: ["true"] },
        },
      ]

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/trace:
    endpoint: tracetest-agent:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [otlp]
    traces/agent:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [otlp/trace]
