version: '3'

services:
  k6-tracetest:
    build:
      context: .
      dockerfile: k6.Dockerfile
    environment:
      XK6_TRACETEST_API_TOKEN: ${TRACETEST_API_TOKEN}
      POKESHOP_DEMO_URL: ${POKESHOP_DEMO_URL}
    volumes:
      - ./test/k6/add-pokemon.js:/import-pokemon.js
