version: '3.5'
name: pokeshop

services:
  db:
    image: postgres:14
    # ports:
    #   - 5434:5432
    environment:
      POSTGRES_USER: ashketchum
      POSTGRES_PASSWORD: squirtle123
      POSTGRES_DB: pokeshop
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 1s
      timeout: 5s
      retries: 60

  cache:
    image: redis:6
    # ports:
    #   - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 60

  queue:
    image: rabbitmq:3.12
    restart: unless-stopped
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 1s
      timeout: 5s
      retries: 60

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 14250:14250
      - 16685:16685
      - 16686:16686
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'localhost:16686']
      interval: 1s
      timeout: 3s
      retries: 60

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 4317:4317
      - 4318:4318
    command:
      - '--config'
      - '/otel-local-config.yaml'
    volumes:
      - ./collector.config.yaml:/otel-local-config.yaml
    depends_on:
      jaeger:
        condition: service_healthy

  api:
    build: .
    environment:
      REDIS_URL: cache
      DATABASE_URL: postgresql://ashketchum:squirtle123@db:5432/pokeshop?schema=public
      RABBITMQ_HOST: queue
      POKE_API_BASE_URL: https://pokeapi.co/api/v2
      COLLECTOR_ENDPOINT: http://otel-collector:4317
      ZIPKIN_URL: http://localhost:9411
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'localhost:8081/pokemon/healthcheck']
      interval: 1s
      timeout: 3s
      retries: 60
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      queue:
        condition: service_healthy
      jaeger:
        condition: service_healthy
      otel-collector:
        condition: service_started
  rpc:
    build: .
    environment:
      REDIS_URL: cache
      DATABASE_URL: postgresql://ashketchum:squirtle123@db:5432/pokeshop?schema=public
      RABBITMQ_HOST: queue
      POKE_API_BASE_URL: https://pokeapi.co/api/v2
      COLLECTOR_ENDPOINT: http://otel-collector:4317
      ZIPKIN_URL: http://localhost:9411
      NPM_RUN_COMMAND: rpc
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'localhost:8081/pokemon/healthcheck']
      interval: 1s
      timeout: 3s
      retries: 60
    ports:
      - 8082:8082
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      queue:
        condition: service_healthy
      jaeger:
        condition: service_healthy
      otel-collector:
        condition: service_started

  worker:
    build: .
    environment:
      REDIS_URL: cache
      DATABASE_URL: postgresql://ashketchum:squirtle123@db:5432/pokeshop?schema=public
      RABBITMQ_HOST: queue
      POKE_API_BASE_URL: https://pokeapi.co/api/v2
      COLLECTOR_ENDPOINT: http://otel-collector:4317
      ZIPKIN_URL: http://localhost:9411
      NPM_RUN_COMMAND: worker
      SERVICE_NAME: pokeshop-worker
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      queue:
        condition: service_healthy
      jaeger:
        condition: service_healthy
      otel-collector:
        condition: service_started
