version: '3.5'
name: pokeshop

services:
  tracetest-agent:
    image: kubeshop/tracetest-agent:dev
    environment:
      TRACETEST_DEV: ${TRACETEST_DEV}
      TRACETEST_API_KEY: ${TRACETEST_AGENT_API_KEY}
      TRACETEST_SERVER_URL: ${TRACETEST_SERVER_URL}
      TRACETEST_ENVIRONMENT_ID: ${TRACETEST_ENVIRONMENT_ID}
      TRACETEST_TRACE_MODE: ${TRACETEST_TRACE_MODE}

