version: '3.5'
name: pokeshop

services:
  api-ci:
    image: kubeshop/demo-pokemon-api:0.0.10
    environment:
      REDIS_URL: cache
      DATABASE_URL: postgresql://ashketchum:squirtle123@db:5432/pokeshop?schema=public
      RABBITMQ_HOST: queue
      POKE_API_BASE_URL: https://pokeapi.co/api/v2
      ZIPKIN_URL: http://jaeger:9411
    ports:
      - 3001:80
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      queue:
        condition: service_healthy
      jaeger:
        condition: service_healthy