apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cache
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: cache
    spec:
      containers:
        - image: redis:6
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 60
            periodSeconds: 1
            timeoutSeconds: 3
          name: cache
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
