# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cache
  template:
    metadata:
      labels:
        io.kompose.service: cache
    spec:
      containers:
        - image: redis:6
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 60
            periodSeconds: 1
            timeoutSeconds: 3
          name: cache
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always

# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cache
  name: cache
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: cache
