apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
    io.kompose.service: db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
