apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
  labels:
    io.kompose.service: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
