apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  ports:
    - name: "55679"
      port: 55679
      targetPort: 55679
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "4318"
      port: 4318
      targetPort: 4318
  selector:
    io.kompose.service: otel-collector
