apiVersion: v1
data:
  collector.config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: ${JAEGER_ENDPOINT}
        tls:
          insecure: true
      otlp/trace:
        endpoint: ${TRACETEST_AGENT_ENDPOINT}
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, jaeger]
        traces/1:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/trace]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: otel-collector
  name: otel-collector-cm0
