apiVersion: v1
data:
  collector.config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
              endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      otlp/jaeger:
        endpoint: ${JAEGER_ENDPOINT}
        tls:
          insecure: true
      otlp/tracetest:
        endpoint: ${TRACETEST_AGENT_ENDPOINT}
        tls:
          insecure: true

    service:
      pipelines:
        traces/jaeger:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp/jaeger]
        traces/tracetest:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tracetest]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: otel-collector
  name: otel-collector-cm0
