# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rpc
  name: rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rpc
  template:
    metadata:
      labels:
        io.kompose.service: rpc
    spec:
      containers:
        - env:
            - name: NPM_RUN_COMMAND
              value: rpc
            - name: COLLECTOR_ENDPOINT
              value: http://otel-collector.default.svc.cluster.local:4317
            - name: DATABASE_URL
              value: postgresql://ashketchum:squirtle123@db:5432/pokeshop?schema=public
            - name: POKE_API_BASE_URL
              value: https://pokeapi.co/api/v2
            - name: RABBITMQ_HOST
              value: guest:guest@queue
            - name: REDIS_URL
              value: cache
            - name: RPC_PORT
              value: "8082"
          image: kubeshop/demo-pokemon-api:latest
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - wget
                - --spider
                - 0.0.0.0:8081/pokemon/healthcheck
            failureThreshold: 60
            periodSeconds: 1
            timeoutSeconds: 3
          name: rpc
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always

# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rpc
  name: rpc
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: rpc
