export enum CustomTags {
  HTTP_RESPONSE_BODY = 'http.response.body',
  RPC_RESPONSE_BODY = 'rpc.response.body',
  RPC_REQUEST_BODY = 'rpc.request.body',
  HTTP_REQUEST_BODY = 'http.request.body',
  VALIDATION_IS_VALID = 'validation.is_valid',
  VALIDATION_ERRORS = 'validation.errors',
  HTTP_REQUEST_HEADER = 'http.request.header',
  HTTP_RESPONSE_HEADER = 'http.response.header',
  DB_PAYLOAD = 'db.payload',
  DB_RESULT = 'db.result',
  MESSAGING_PAYLOAD = 'messaging.payload',
  MESSAGING_HEADER = 'messaging.header',
  CACHE_HIT = 'cache.hit',
}
