apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokemon-api.fullname" . }}
  labels:
    {{- include "pokemon-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
    - port: {{ .Values.service.rpcPort }}
      targetPort: 8082
      protocol: TCP
      name: grpc
  selector:
    {{- include "pokemon-api.selectorLabels" . | nindent 4 }}
