Resources:
  OtelConfigParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: pokeshop-otel-config
      Type: String
      Tier: Standard
      DataType: text
      Value: |
        receivers:
          otlp:
            protocols:
              grpc:
              http:
        processors:
          batch:
            timeout: 100ms
          probabilistic_sampler:
            hash_seed: 22
            sampling_percentage: 100
        exporters:
          otlp/data-prepper:
            endpoint: localhost:21890
            tls:
              insecure: true
              insecure_skip_verify: true
        service:
          pipelines:
            traces:
              receivers: [otlp]
              processors: [probabilistic_sampler, batch]
              exporters: [otlp/data-prepper]

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: [OtelConfigParameter]
    Properties:
      Family: otel-sidecar-service
      TaskRoleArn: !Ref ECSTaskRole
      ExecutionRoleArn: !Ref ECSExecutionRole
      NetworkMode: host
      ContainerDefinitions:
        - Command: ["--config=/etc/ecs/ecs-default-config.yaml"]
          Image: "amazon/aws-otel-collector:latest"
          Name: aws-collector
          Secrets:
            - Name: AOT_CONFIG_CONTENT
              ValueFrom: !Ref OtelConfigParameter
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "True"
              awslogs-group: /ecs/aws-collector
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 2000
              Protocol: udp
              ContainerPort: 2000
            - HostPort: 4317
              Protocol: tcp
              ContainerPort: 4317
            - HostPort: 8125
              Protocol: udp
              ContainerPort: 8125
      Memory: "2048"
      RequiresCompatibilities:
        - EC2
      Cpu: "512"
  OtelECSReplicaService:
    Type: "AWS::ECS::Service"
    Properties:
      TaskDefinition: !Ref ECSTaskDefinition
      Cluster: !Ref ECSCluster
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      ServiceName: otel-sidecar-service
  ECSTaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: Allows ECS tasks to call AWS services on your behalf.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: AWSOpenTelemetryPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "logs:PutLogEvents"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DescribeLogStreams"
                  - "logs:DescribeLogGroups"
                  - "xray:PutTraceSegments"
                  - "xray:PutTelemetryRecords"
                  - "xray:GetSamplingRules"
                  - "xray:GetSamplingTargets"
                  - "xray:GetSamplingStatisticSummaries"
                  - "ssm:GetParameters"
                Resource: "*"
      RoleName: !Join
        - "-"
        - - OtelTaskRole
          - !Ref "AWS::StackName"

  ECSExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: >-
        Allows ECS container agent makes calls to the Amazon ECS API on your
        behalf.
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
      RoleName: !Join
        - "-"
        - - OtelExecutionRole
          - !Ref "AWS::StackName"
