Resources:
  OtelConfigParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: pokeshop-otel-config
      Type: String
      Tier: Standard
      DataType: text
      Value: |
        receivers:
          otlp:
            protocols:
              grpc:
              http:
        processors:
          batch:
            timeout: 100ms
          probabilistic_sampler:
            hash_seed: 22
            sampling_percentage: 100
        exporters:
          otlp/data-prepper:
            endpoint: localhost:21890
            tls:
              insecure: true
              insecure_skip_verify: true
        service:
          pipelines:
            traces:
              receivers: [otlp]
              processors: [probabilistic_sampler, batch]
              exporters: [otlp/data-prepper]

  TracetestTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: tracetest
      TaskRoleArn: !Ref ECSTaskRole
      ExecutionRoleArn: !Ref ECSExecutionRole
      NetworkMode: host
      Memory: "3040"
      RequiresCompatibilities:
        - EC2
      Cpu: "2000"
      Volumes:
        - Name: config
          DockerVolumeConfiguration:
            Scope: shared
            Autoprovision: true
            Driver: local
        - Name: tracetest-config
          DockerVolumeConfiguration:
            Scope: shared
            Autoprovision: true
            Driver: local
      ContainerDefinitions:
        - Image: "public.ecr.aws/opensearchproject/data-prepper:latest"
          Name: data-prepper
          MountPoints:
            - SourceVolume: config
              ContainerPath: /usr/share/data-prepper
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "True"
              awslogs-group: /ecs/data-prepper
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 4900
              Protocol: tcp
              ContainerPort: 4900
            - HostPort: 21890
              Protocol: tcp
              ContainerPort: 21890
        - Image: "amazon/aws-otel-collector:latest"
          Command: ["--config=/etc/ecs/ecs-default-config.yaml"]
          Name: aws-collector
          Secrets:
            - Name: AOT_CONFIG_CONTENT
              ValueFrom: !Ref OtelConfigParameter
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "True"
              awslogs-group: /ecs/aws-collector
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 2000
              Protocol: udp
              ContainerPort: 2000
            - HostPort: 4317
              Protocol: tcp
              ContainerPort: 4317
            - HostPort: 8125
              Protocol: udp
              ContainerPort: 8125
          DependsOn:
            - ContainerName: data-prepper
              Condition: START
        - Image: "public.ecr.aws/n6u9v0x8/tracetest:v0.7.6"
          Name: tracetest
          MountPoints:
            - SourceVolume: tracetest-config
              ContainerPath: /app
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "True"
              awslogs-group: /ecs/tracetest
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          PortMappings:
            - HostPort: 11633
              Protocol: tcp
              ContainerPort: 11633
          DependsOn:
            - ContainerName: aws-collector
              Condition: START

  TracetestService:
    Type: "AWS::ECS::Service"
    Properties:
      TaskDefinition: !Ref TracetestTaskDefinition
      Cluster: !Ref ECSCluster
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      ServiceName: tracetest

  ECSTaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: Allows ECS tasks to call AWS services on your behalf.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: AWSOpenTelemetryPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "logs:PutLogEvents"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DescribeLogStreams"
                  - "logs:DescribeLogGroups"
                  - "xray:PutTraceSegments"
                  - "xray:PutTelemetryRecords"
                  - "xray:GetSamplingRules"
                  - "xray:GetSamplingTargets"
                  - "xray:GetSamplingStatisticSummaries"
                  - "ssm:GetParameters"
                Resource: "*"
      RoleName: !Join
        - "-"
        - - OtelTaskRole
          - !Ref "AWS::StackName"

  ECSExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: >-
        Allows ECS container agent makes calls to the Amazon ECS API on your
        behalf.
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
      RoleName: !Join
        - "-"
        - - OtelExecutionRole
          - !Ref "AWS::StackName"

Outputs:
  TracetestServiceName:
    Description: The Public IP from the Container Instance
    Value: !GetAtt "TracetestService.Name"
