scheme: https
endpoint: api.tracetest.io
serverPath: /api
organizationID: ttorg_d93f8634acf22530
environmentID: ttenv_82d7c803788157a6
jwt: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbnZpcm9ubWVudF9pZCI6IiIsImV4cCI6MTcyNzI4MjY1NywiaWF0IjoxNjk1NzQ2NjU3LCJqdGkiOiJ0dHRva2VuX2Q5ZGI3MWQ3MDg5YmM2MzkiLCJvcmdhbml6YXRpb25faWQiOiIiLCJ1c2VyX2lkIjoiZTdlZWRlZTYtNzZmOC00OTc1LWI3MmQtOWI2MTFkZGI4N2ZhIn0.KW-arj9XTVD8OeKBvTb9Bv3AhhrVIhgQZTJdRhfYf9GwlsduUaUGrs6C3HEzO2TTpovd827trTr8I9B5LoO6wzfYrQpICXWvSuH7GkQ4wEdmgux6nOC8j2uKYKW5zRgzG8AJVXvjg9uImGe5pk8aWek_N4gRL9H1-rsRPcUSXh3Vqo3x5MdEffNfhTnCkg8ZgvN_YgLg8ZKDLkBAg6G1tR219K8x0-HFPGIcUbI-2uvEs3Vl_QydwCSH5or5U9tsk4MlvJNDMaqmBHdxKAQhkF5NpzkpBppOHcJfKcG3ybH_IXzi7LCg55YjHfBPt9tDGVpZb5GDNnQ0jkDNtcSk4A
agentEndpoint: api.tracetest.io:8091
uIEndpoint: https://app.tracetest.io/
