scheme: https
endpoint: api-stage.tracetest.io
serverPath: /api
organizationID: ttorg_cc188ef9fea96fd0
environmentID: ttenv_68bf9f8d81a18f42
jwt: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbnZpcm9ubWVudF9pZCI6IiIsImV4cCI6MTcyNzI3NzMzOSwiaWF0IjoxNjk1NzQxMzM5LCJqdGkiOiJ0dHRva2VuX2ZkMDRkMmNkODJiY2JhNGUiLCJvcmdhbml6YXRpb25faWQiOiIiLCJ1c2VyX2lkIjoiMzQxOTk3NTUtYWExZi00ZmI1LTk1ZmItNTBjODZhNTE1MGM0In0.T5NOyd7toz6M4Zze-zuLHSknSrr3KcqRTu7iD_wrRTs1Ay16_bkkhz_eGDpqSjrf6XFg4-Knu6TRtz96ZJ7TZESCDEZu8oDXhl-l4JuY4VyI5n_PZt2gFooiXTMdPX36Z-P5QMq4arveGfIDb2BP0Wy_6k7mex7qqQhqsv8rZ0UO38_rd4hUSUDXNx2QC1pms9dPyMv1szahFbysjtdzCCvvCIEvDvUBNI70kxVdtTZZ6itB_rA74mSInPZW_KZiVS_6z7Xe7ibr7hALGLeMziqIYk4eJikEechaJwcg9fU1JoP0v-aYpVpaXHf8pH82HiREpkphcs92_2Mjo3kZ7g
agentEndpoint: api-stage.tracetest.io:443
uIEndpoint: https://app-stage.tracetest.io/
