name: Artillery Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run ./test/artillery/import-pokemon.yml
        env:
          ARTILLERY_PLUGIN_PATH: ${{ github.workspace }}/node_modules/
      - name: Send message on Slack in case of failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # check the block kit builder docs to understand how it works
          # and how to modify it: https://api.slack.com/block-kit
          payload: |
            {
              "text": ":warning: Synthetic Monitoring failed for *Artillery with Pokeshop*. <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SYNTETIC_MONITORING_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
