name: Artillery Socket.IO Load Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # every hour

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run ./test/artillery/import-pokemon.yml
