name: Cypress Tests

on:
  # allows the manual trigger
  workflow_dispatch:

  schedule:
    - cron: '0 */1 * * *' # every hour

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          TRACETEST_API_TOKEN: ${{secrets.TRACETEST_TOKEN}}
          POKESHOP_DEMO_URL: ${{secrets.POKESHOP_DEMO_URL}}
