name: Cypress Tests

on:
  # allows the manual trigger
  workflow_dispatch:

  # schedule:
  #   - cron: '0 */1 * * *' # every hour

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          TRACETEST_API_TOKEN: ${{secrets.TRACETEST_TOKEN}}
          POKESHOP_DEMO_URL: ${{secrets.POKESHOP_DEMO_URL}}
          
      - name: Send message on Slack in case of failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # check the block kit builder docs to understand how it works
          # and how to modify it: https://api.slack.com/block-kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":warning: Synthetic Monitoring Alert - E2E Cypress - Pokeshop Demo :warning:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\nFailed"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Pipeline:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SYNTETIC_MONITORING_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
