name: Cypress Tests Stage

on:
  # allows the manual trigger
  workflow_dispatch:

  schedule:
    - cron: '*/15 * * * *' # Run every 20 minutes

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          TRACETEST_API_TOKEN: ${{secrets.TRACETEST_TOKEN_STAGE}}
          POKESHOP_DEMO_URL: ${{secrets.POKESHOP_DEMO_URL_STAGE}}
          TRACETEST_SERVER_URL: https://app-stage.tracetest.io
          
      - name: Send message on Slack in case of failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":warning: Synthetic Monitoring failed for *Cypress e2e with Pokeshop* on *stage*. <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SYNTETIC_MONITORING_SLACK_WEBHOOK_URL_STAGE }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
