name: K6 Tests Stage
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Run every 20 minutes

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker compose -f docker-compose.k6.workflows.yml run k6-tracetest
        env:
          TRACETEST_API_TOKEN: ${{secrets.TRACETEST_TOKEN_STAGE}}
          POKESHOP_DEMO_URL: ${{secrets.POKESHOP_DEMO_URL_STAGE}}
          TRACETEST_SERVER_URL: https://app-stage.tracetest.io

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.k6.workflows.yml down
      - name: Send message on Slack in case of failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # check the block kit builder docs to understand how it works
          # and how to modify it: https://api.slack.com/block-kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":warning: Synthetic Monitoring Alert - K6 - Pokeshop Demo :warning:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\nFailed"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Pipeline:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SYNTETIC_MONITORING_SLACK_WEBHOOK_URL_STAGE }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
